#### 1. Replace all odd numbers in the given array [1,3,4,5,6,7,11,21] with -1

In [2]:
import numpy as np

In [6]:
a=np.array([1,3,4,5,6,7,11,21])
b=[]
for i in a:
    if i%2 != 0:
        b.append(-1)
    else:
        b.append(i)
print(b)    

[-1, -1, 4, -1, 6, -1, -1, -1]


In [12]:
x=np.array([10,27,50,2])
y=[]
for i in x:
    if i >=25:
           y.append(-1)
    else:
           y.append(i)
print(y)           
           
           

[10, -1, -1, 2]


* take full 1d array with element 9 in it,
* a. access single element, 
* b. access multiple elements.
* c. slice out a 1d array
* d. on the previously sliced array apply the slicing again.

In [7]:
array1D=np.array([1,2,3,4,5,6,7,8,9])

In [8]:
#access single element

In [9]:
array1D[3]

4

In [10]:
array1D[6]

7

In [11]:
# access multiple element

In [13]:
array1D[[1,4]]

array([2, 5])

In [14]:
array1D[[2,5,7]]

array([3, 6, 8])

In [15]:
#slice out a 1D Array

In [16]:
array1D[1:8]

array([2, 3, 4, 5, 6, 7, 8])

In [17]:
#on the previously sliced array apply the slicing again.

In [18]:
array1D[1:8][3:6]

array([5, 6, 7])

### take 2d diagonal matrix with diagonal elements (1,2,3,,4,5,6)

* a. access single row
* b. access multiple rows
* c. access single element
* d. access multiple elements
* e. slice out a 2d array
* f. on the previously sliced array apply the slicing again.


In [21]:
array2D=np.diag(range(1,7))
                 

In [22]:
array2D

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [23]:
#access a single row

In [24]:
array2D[0]

array([1, 0, 0, 0, 0, 0])

In [25]:
array2D[1]

array([0, 2, 0, 0, 0, 0])

In [26]:
#access multiple rows

In [28]:
array2D[[0,1,2]]

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0]])

In [29]:
#access a single element

In [31]:
array2D[0,0]

1

In [32]:
array2D[1,1]

2

In [40]:
array2D[3,3]

4

In [41]:
#acess a multiple element

In [48]:
array2D[[3,4,5],[3,4,5]]

array([4, 5, 6])

In [49]:
#slice out a 2D array

In [50]:
array2D[1:5]

array([[0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

In [51]:
 #on the previously sliced array apply the slicing again.

In [52]:
array2D[1:5][2:4]

array([[0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

#### construct a 3d array of shape (4,3,5)

* a. access single 2d array
* b. access multiple 2d arrays
* c. access single row
* d. access multiple rows
* e. access single element
* f. access multiple elements
* g. using this syntax arr[: ,: ,:] -- fetch the elements
* h. slice out a 3d array, after slicing this reverse the 2d arrays using arr[][] -- this syntax

In [73]:
array3D=np.arange(60).reshape(4,3,5)

In [74]:
array3D

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]],

       [[45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [55]:
#access single 2d array

In [56]:
array3D[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
array3D[1]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [58]:
#access multiple 2d arrays

In [77]:
array3D[[0,1]]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [70]:
#access single row

In [76]:
array3D[0,1]

array([5, 6, 7, 8, 9])

In [78]:
#accessing multiple row

In [83]:
array3D[[0,1],[1,1]]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [84]:
#accessing single element

In [85]:
array3D[1,2,3]

28

In [87]:
#accessing multiple element

In [89]:
array3D

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]],

       [[45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [92]:
array3D[[1,2,3],[1,2,2],[1,2,3]]

array([21, 42, 58])

In [93]:
#. using this syntax arr[: ,: ,:] -- fetch the elements

In [98]:
array3D[1:2,2:3,1:2]

array([[[26]]])